---
################################################################################
# Setup configuration for Dotbot
#
# @see https://github.com/anishathalye/dotbot for more info
################################################################################

- defaults:
    shell:
      quiet: false
      description: <<<<<<<<####### DESCRIPTION MISSING

- shell:
    - /usr/bin/rm -rf ~/github.com/dracula
    - /usr/bin/mkdir -p ~/github.com/dracula
    - git clone https://github.com/dracula/dircolors ~/github.com/dracula/dircolors
    - git clone https://github.com/dracula/xresources.git ~/github.com/dracula/xresources
    - git clone https://github.com/dracula/apt ~/github.com/dracula/apt
    - git clone https://github.com/dracula/gtk ~/github.com/dracula/gtk
    - sudo cp ~/github.com/dracula/apt/50dracula-colors.conf /etc/apt/apt.conf.d/50dracula-colors.conf

- link:
    ~/.dircolors: ~/github.com/dracula/dircolors/.dircolors
    ~/.Xresources: ~/github.com/dracula/xresources/Xresources
