[theme]
name = "dracula"

[colors]
AlertInfo = "#50FA7B"
AlertWarn = "#F1FA8C"
AlertError = "#FF5555"
Annotation = "#8BE9FD"
Base = "#F8F8F2"
Guidance = "#6272A4"
Important = "#FFB86C"
Title = "#FF79C6"
